// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cov_r2C
NumericVector Cov_r2C(NumericVector n, NumericVector R, NumericVector E, int dummy_nthread);
RcppExport SEXP _eigvaldisp_Cov_r2C(SEXP nSEXP, SEXP RSEXP, SEXP ESEXP, SEXP dummy_nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type dummy_nthread(dummy_nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Cov_r2C(n, R, E, dummy_nthread));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eigvaldisp_Cov_r2C", (DL_FUNC) &_eigvaldisp_Cov_r2C, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_eigvaldisp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
