# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum of covariances of squared correlations
#'
#' \code{Cov.r2C()} calculates (twice) sum of covariances of
#' all non-redundant pairs of squared correlation coefficients.
#' This is an internal C++ function to be used in within \code{AVar.VRr_pfc()}
#' with the package \code{Rcpp}.
#'
#' Primarily for internal use.
#'
#' It is assumed that \code{E} has the form of
#' \code{matrix(sapply(n, Exv.r1, x = R[upper.tri(R)]), ncol = length(n))}.
#'
#' \code{R} and \code{E} are read as NumericVector rather than
#' NumericMatrix to save a modest amount of time
#'
#' @param n
#'   Degrees of freedom (not sample sizes); numeric of length 1 or more.
#' @param R
#'   Population correlation matrix; assumed to be validly constructed;
#'   numeric of length \code{p * p}
#' @param E
#'   Matrix of expectation of correlation coefficients corresponding to
#'   the upper triangular of \code{R}; numeric of length
#'   \code{p * (p - 1) / 2 * length(n)}.
#'
#' @return
#' A numeric vector of \eqn{\sum 2 Cov(r_{ij}, r_{kl})},
#' corresponding to \code{n}.
#'
#' @seealso \link{Exv.VXx}, \link{AVar.VRr_xx}
#'
Cov_r2C <- function(n, R, E) {
    .Call(`_eigvaldisp_Cov_r2C`, n, R, E)
}

